version: '3.9'

services:

  gateway:
    image: nginx:stable-alpine
    container_name: api-gateway
    ports:
      - "80:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - anonymous-service
      - organization-service
      - problem-service
      - subscription-service
      - suggestion-box-service
      - billing-notification-service
      - system-notification-service

  anonymous-service:
    build: ./AnonymousUserService
    container_name: anonymous-service
    expose:
      - "8080"

  organization-service:
    build: ./OrganizationService
    container_name: organization-service
    expose:
      - "8080"

  problem-service:
    build: ./ProblemService
    container_name: problem-service
    expose:
      - "8080"

  subscription-service:
    build: ./SubscriptionService
    container_name: subscription-service
    expose:
      - "8080"

  suggestion-box-service:
    build: ./SuggestionBoxService
    container_name: suggestion-box-service
    expose:
      - "8080"

  billing-notification-service:
    build: ./BillingNotificationService
    container_name: billing-notification-service
    expose:
      - "8080"

  system-notification-service:
    build: ./SystemNotificationService
    container_name: system-notification-service
    expose:
      - "8080"