worker_processes auto;

events {
    worker_connections 1024;
}

http {

    include       mime.types;
    default_type  application/json;

    sendfile        on;
    keepalive_timeout  65;

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    upstream anonymous_service {
        server anonymous-service:8080;
    }

    upstream organization_service {
        server organization-service:8080;
    }

    upstream problem_service {
        server problem-service:8080;
    }

    upstream subscription_service {
        server subscription-service:8080;
    }

    upstream suggestion_box_service {
        server suggestion-box-service:8080;
    }

    upstream billing_notification_service {
        server billing-notification-service:8080;
    }

    upstream system_notification_service {
        server system-notification-service:8080;
    }

    server {
        listen 80;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        location /api/v1/anonymous/ {
            proxy_pass http://anonymous_service/;
        }

        location /api/v1/organizations/ {
            proxy_pass http://organization_service/;
        }

        location /api/v1/problems/ {
            proxy_pass http://problem_service/;
        }

        location /api/v1/subscriptions/ {
            proxy_pass http://subscription_service/;
        }

        location /api/v1/suggestions/ {
            proxy_pass http://suggestion_box_service/;
        }

        location /api/v1/billing/ {
            proxy_pass http://billing_notification_service/;
        }

        location /api/v1/system-notifications/ {
            proxy_pass http://system_notification_service/;
        }

        location /health {
            return 200 'API Gateway OK';
        }
    }
}