// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SuggestionService.Migrations
{
    [DbContext(typeof(SuggestionContext))]
    partial class SuggestionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AnonymousDomain.Models.AnonymousUser.AnonymousUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoxAccessLinkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BoxAccessLinkId");

                    b.ToTable("AnonymousUsers");
                });

            modelBuilder.Entity("AnonymousDomain.Models.AnonymousUser.BoxAccessLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("BoxAccessLink");
                });

            modelBuilder.Entity("AnonymousDomain.Models.Attachment.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ProblemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuggestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("SuggestionId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("AnonymousDomain.Models.Suggestion.Suggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnonymousUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SuggestionBoxId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("AnonymousUserId");

                    b.ToTable("Suggestions");
                });

            modelBuilder.Entity("AnonymousDomain.Models.Suggestion.SuggestionCategories", b =>
                {
                    b.Property<Guid>("SuggestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SuggestionCategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SuggestionId", "SuggestionCategoryId");

                    b.HasIndex("SuggestionCategoryId");

                    b.ToTable("SuggestionCategoriesJoin");
                });

            modelBuilder.Entity("AnonymousDomain.Models.Suggestion.SuggestionCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("SuggestionCategories");
                });

            modelBuilder.Entity("AnonymousDomain.Models.Suggestion.SuggestionComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommentAuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<Guid?>("SuggestionCommentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SuggestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("CommentAuthorId");

                    b.HasIndex("SuggestionCommentId");

                    b.HasIndex("SuggestionId");

                    b.ToTable("SuggestionComments");
                });

            modelBuilder.Entity("AnonymousDomain.Models.Suggestion.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SuggestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VoteAuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SuggestionId");

                    b.HasIndex("VoteAuthorId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("AnonymousDomain.Models.AnonymousUser.AnonymousUser", b =>
                {
                    b.HasOne("AnonymousDomain.Models.AnonymousUser.BoxAccessLink", null)
                        .WithMany()
                        .HasForeignKey("BoxAccessLinkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AnonymousDomain.Models.Attachment.Attachment", b =>
                {
                    b.HasOne("AnonymousDomain.Models.Suggestion.Suggestion", null)
                        .WithMany()
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("AnonymousDomain.Models.Suggestion.Suggestion", b =>
                {
                    b.HasOne("AnonymousDomain.Models.AnonymousUser.AnonymousUser", null)
                        .WithMany()
                        .HasForeignKey("AnonymousUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AnonymousDomain.Models.Suggestion.SuggestionCategories", b =>
                {
                    b.HasOne("AnonymousDomain.Models.Suggestion.SuggestionCategory", null)
                        .WithMany()
                        .HasForeignKey("SuggestionCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnonymousDomain.Models.Suggestion.Suggestion", null)
                        .WithMany()
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnonymousDomain.Models.Suggestion.SuggestionComment", b =>
                {
                    b.HasOne("AnonymousDomain.Models.AnonymousUser.AnonymousUser", null)
                        .WithMany()
                        .HasForeignKey("CommentAuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AnonymousDomain.Models.Suggestion.SuggestionComment", null)
                        .WithMany()
                        .HasForeignKey("SuggestionCommentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AnonymousDomain.Models.Suggestion.Suggestion", null)
                        .WithMany()
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AnonymousDomain.Models.Suggestion.Vote", b =>
                {
                    b.HasOne("AnonymousDomain.Models.Suggestion.Suggestion", null)
                        .WithMany()
                        .HasForeignKey("SuggestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AnonymousDomain.Models.AnonymousUser.AnonymousUser", null)
                        .WithMany()
                        .HasForeignKey("VoteAuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
